### ISSUE TITLE
Adding status and municipality filter to "Business Types" chart.

### ISSUE THREAD

**Issue by diamanthaxhimusa** [opendatakosovo/open-arbk#15]

**Comment by KosovareSahatqija** [comment]
Please, @diamanthaxhimusa review this issue again because I have reviewed and the button is not working. 
When I inspect element I can see a bunch of errors in console.
<img width="1210" alt="screen shot 2017-05-11 at 12 32 16 am" src="https://cloud.githubusercontent.com/assets/16719237/25924153/8c98337a-35e1-11e7-8101-db5ec5185c35.png">
