### ISSUE TITLE
Create footer with ODK logo.

### ISSUE THREAD

**Issue by georgeslabreche** [opendatakosovo/open-arbk#30]

**Comment by KosovareSahatqija** [comment]
@diamanthaxhimusa I think the content of the footer should be smaller and the description of the organization should be in Albanian since all the site is in the Albanian
<img width="1280" alt="screen shot 2017-05-15 at 10 50 14 am" src="https://cloud.githubusercontent.com/assets/16719237/26049782/7b3830fc-395c-11e7-8a6c-0d162fd73725.png">
 language.

**Comment by KosovareSahatqija** [comment]
@diamanthaxhimusa I am sending back to not accepted because the footer is too large. Example bellow shows the mobile view of the footer (one-page footer)

<img width="317" alt="screen shot 2017-05-16 at 6 44 21 pm" src="https://cloud.githubusercontent.com/assets/16719237/26117786/e56d8fc4-3a67-11e7-9960-d6333e8e51dd.png">
